# Generated by Django 4.2 on 2026-05-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_passwordresetotp_attempts_passwordresetotp_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='used',
            new_name='is_used',
        ),
    ]
